# 05: Bagging and random forests

In [1]:
%matplotlib inline

import numpy as np
import pandas as pd
import scipy.stats as st
import matplotlib.pyplot as plt

import mylib as my

The goal of ensemble methods to to reduce bias and/or variance help prevent overfitting. In this notebook we look at two ensemble methods: bagging and random forests.

## Bootstrap samples
Let's start by seeing how we can draw a bootstrap sample given a dataset $D$. A bootstrap sample is a sample drawn randomly with replacement from the given dataset such that the size of the sample is the same as the size of the original dataset. That means some examples will show up multiple times in the drawn sample.

In the example below, we are using a subset of the car dataset with classes indicating whether the car is in acceptable or unacceptable condition. The description of the original car dataset can be found at [this page](https://archive.ics.uci.edu/ml/datasets/Car+Evaluation).

In [2]:
df = pd.read_csv('datasets/ua_car.csv')
ds = my.DataSet(df, y=True)
print(df.iloc[:,-1].value_counts())

unacc    384
acc      384
Name: y, dtype: int64


In [3]:
train, test = ds.train_test_split(test_portion=.25, shuffle=True)
print(train)
print(test)

    buying maintenance  doors persons luggage safety      y
383    low       vhigh  5more       4   small    low  unacc
541   high         low      3    more     med   high    acc
233  vhigh         low      4       2     big   high  unacc
210   high       vhigh  5more       2     big    med  unacc
181   high       vhigh      2       4     med    low  unacc
..     ...         ...    ...     ...     ...    ...    ...
376    med         low      4       2     big    low  unacc
203  vhigh       vhigh  5more    more     big   high  unacc
411  vhigh         med  5more       4     med    med    acc
241    med       vhigh  5more       2   small    med  unacc
101  vhigh         med      2    more     big    low  unacc

[576 rows x 7 columns]
    buying maintenance  doors persons luggage safety      y
235  vhigh         med      2       2     big    med  unacc
410  vhigh         med  5more       4   small   high    acc
370  vhigh         low      3       2     med    med  unacc
46     med      

Given the above training set, we can draw a bootstrap sample like this:

In [4]:
sample_indexes = np.random.randint(0, train.N, size=train.N)
bootstrap_sample = train.examples.iloc[sample_indexes, :]
bootstrap_sample

buying maintenance  doors persons luggage safety      y
563   high         low  5more    more     big   high    acc
184  vhigh         med      4    more     med    low  unacc
483   high        high  5more       4     med    med    acc
17   vhigh       vhigh      2    more     big   high  unacc
337    med         low      2       4   small    low  unacc
..     ...         ...    ...     ...     ...    ...    ...
685    low       vhigh      2    more     big   high    acc
656    med         med      4       4     big    med    acc
564    med       vhigh      2       4   small   high    acc
116    med         low      3       4     med    low  unacc
312    med         low      3    more     med    low  unacc

[576 rows x 7 columns]

of which:

In [5]:
print("{:.2%}".format(
    pd.unique(bootstrap_sample.index).shape[0] / len(bootstrap_sample)), 'are unique examples')
print("{:.2%}".format(
    1 - pd.unique(bootstrap_sample.index).shape[0] / len(bootstrap_sample)), 'are repeated examples')

64.93% are unique examples
35.07% are repeated examples


Sometimes, it's useful to be able to identify the examples that are included in a given sample and those that aren't. Here are two functions for doing so.

In [6]:
def examples_in_sample(examples, sample):
    return examples[examples.index.isin(sample.index)]

def examples_not_in_sample(examples, sample):
    return examples[~examples.index.isin(sample.index)]

Here are the examples from the training set what are in the above bootstrap sample:

In [7]:
examples_in_sample(train.examples, bootstrap_sample)

buying maintenance  doors persons luggage safety      y
541   high         low      3    more     med   high    acc
233  vhigh         low      4       2     big   high  unacc
210   high       vhigh  5more       2     big    med  unacc
119   high       vhigh  5more       4   small    low  unacc
740    low        high  5more       4   small    med    acc
..     ...         ...    ...     ...     ...    ...    ...
557   high         low  5more       4     big    med    acc
677    med         low  5more       4   small    med    acc
376    med         low      4       2     big    low  unacc
203  vhigh       vhigh  5more    more     big   high  unacc
411  vhigh         med  5more       4     med    med    acc

[374 rows x 7 columns]

And here are the examples from the training set that are not in the above bootstrap sample:

In [66]:
examples_not_in_sample(train.examples, bootstrap_sample)

buying maintenance  doors persons luggage safety      y
383    low       vhigh  5more       4   small    low  unacc
181   high       vhigh      2       4     med    low  unacc
455  vhigh         low  5more    more     big   high    acc
663    med         med  5more       4     med    med    acc
45   vhigh       vhigh      2       2     big   high  unacc
..     ...         ...    ...     ...     ...    ...    ...
645    med         med      3       4   small   high    acc
272    low         low      2       2     med   high  unacc
453  vhigh         low  5more    more     med   high    acc
241    med       vhigh  5more       2   small    med  unacc
101  vhigh         med      2    more     big    low  unacc

[202 rows x 7 columns]

## Bagging
The simplest form of ensemble methods is called **bagging** which stands for **bootstrap aggregation**. The idea is simple:
* take $T$ bootstrap samples from the given dataset
* for each bootstrap sample, train a decision tree DT
* the predicted label of an unseen example is the average(for regression problems) or the plurality vote (for classification problems) of all the output predicted by all the trained $T$ trees.

Here is a simple implementation of bagging.

In [9]:
class Bagger:
    def __init__(self, dataset, nTrees):
        self.ds = dataset
        self.nTrees = nTrees
        self.classifiers = []
        self.samples = []
        self.make_trees()

    def make_trees(self):
        indexes = np.random.randint(0, self.ds.N,(self.ds.N,self.nTrees))
        for i in range(self.nTrees):
            # Create bootstrap samples one for each tree
            self.samples.append(self.ds.examples.iloc[indexes[:, i], :])

            # Build classifiers
            self.classifiers.append(my.DecisionTreeClassifier(my.DataSet(self.samples[i])))

    def predict(self, unseen):
        """
        Returns the most probable label (or class) for each unseen input. The
        unseen needs to be a data series with the same features (as indexes) as the 
        training data. It can also be a data frame with the same features as 
        the training data.
        """
        if unseen.ndim == 1:
            classes = np.array([ dt.predict(unseen) for dt in self.classifiers ])
            classes = classes[classes != None]
            return st.mode(classes).mode[0]
        
        else:
            return np.array([self.predict(unseen.iloc[i,:]) for i in range(len(unseen))]) 

## Random forests
Bagging is not exclusive to decision trees; it can be used with other models. Random forests is bagging applied exclusively to decision trees. In addition to obtaining $T$ random bootstrap samples, it also requires what is sometimes called **feature bagging**. Feature bagging requires that only a randomly selected subset of the features is considered at each node during the construction of the decision tree. 

That means we need to modify our implementation of the decision tree such that it takes a numeric parameter named `nFeatures` which defaults to 0. If `nFeatures` is 0, then the tree functions as normal. If not, it picks this many features randomly and only consider the best of those during the construction of the tree. The provided `my.DecisionTreeClassifier` class already has these changes.

For prediction, a plurality vote of the $T$ predicted labels is returned. Here is a simple implementing of random forests. Think about the similarities and differences between these too classes.

In [10]:
class RandomForest:
    def __init__(self, dataset, nTrees, nFeatures=0):
        self.ds = dataset
        self.nTrees = nTrees
        self.nFeatures = nFeatures
        self.classifiers = []
        self.samples = []
        self.make_forest()

    def make_forest(self):
        indexes = np.random.randint(0, self.ds.N,(self.ds.N,self.nTrees))
        for i in range(self.nTrees):
            # Create bootstrap samples one for each tree
            self.samples.append(self.ds.examples.iloc[indexes[:, i], :])

            # Build classifiers
            self.classifiers.append(my.DecisionTreeClassifier(my.DataSet(self.samples[i]), nFeatures=self.nFeatures))

    def predict(self, unseen):
        """
        Returns the most probable label (or class) for each unseen input. The
        unseen needs to be a data series with the same features (as indexes) as the 
        training data. It can also be a data frame with the same features as 
        the training data.
        """
        if unseen.ndim == 1:
            classes = np.array([ dt.predict(unseen) for dt in self.classifiers ])
            classes = classes[classes != None]
            return st.mode(classes).mode[0]
        
        else:
            return np.array([self.predict(unseen.iloc[i,:]) for i in range(len(unseen))]) 

## Testing

In [11]:
dt = my.DecisionTreeClassifier(train)
cm = my.confusion_matrix(test.target, dt.predict(test.examples.iloc[:,:-1]))
accuracy = np.trace(cm) / np.sum(cm)

print(cm)
print('Decistion tree accuracy: ', accuracy)


bg = Bagger(train, 20)
cm = my.confusion_matrix(test.target, bg.predict(test.examples.iloc[:,:-1]))
accuracy = np.trace(cm) / np.sum(cm)

print(cm)
print('Bagger accuracy: ', accuracy)

rf = RandomForest(train, 20, nFeatures=3)
cm = my.confusion_matrix(test.target, rf.predict(test.examples.iloc[:,:-1]))
accuracy = np.trace(cm) / np.sum(cm)

print(cm)
print('Random forests accuracy: ', accuracy)

[[78  3]
 [12 99]]
Decistion tree accuracy:  0.921875
[[79  2]
 [12 99]]
Bagger accuracy:  0.9270833333333334
[[79  2]
 [20 91]]
Random forests accuracy:  0.8854166666666666


You should try different values for `nTrees` and `nFeatures`. These variables are considered hyperparameters, and cross-validation can be used to determine the best values for them. Common values for `nFeatures` are $\sqrt{m}$ and $log_2(m)$ where $m$ is the number of features.

## Out of bag score
Another way of testing random forests is to calculate the so-called **out-of-bag** score. Such a score does not require splitting the dataset into a training and test sets. One way to calculate it is to identify for each example $x$ in the dataset the list of trees that are trained using samples that do not include it; let's call this list of trees $D_x$. We then call the `predict` method on each tree of $D_x$ to get the list of predicted classes for each of of these out of bag $x$ examples; let's call this list of classes $C_x$. Finally we find the class in $C_x$ that repeats the most and report it as the predicted class of $x$; let's call it $h_x$.

Doing this for each example in the dataset gives us an array of predicted classes, which we can compare against the actual target classes of these examples. Using the confusion matrix we can report the accuracy as the out of bag score.

Notice that the above implementations of `Bagger` and `RandomForest` already give you access to the bootstrap samples and the classifiers that are trained on them. You can use that to find out what sample does not include a given example.

## CHALLENGE
Write a function that calculates the out of bag score as described above given three arguments: a dataset, number of trees (`nTrees`), and number of features (`nFeatures`). The function should use these arguments to create a random forest object to use for calculating this score.

Test and report the out of bag scores for the whole car dataset and for when `nTrees` is 10, 15, and 20.

## Challenge Explained
The fist thing I did is grab a list of lists. This list contains lists of every row used in a tree. For example if we use 10 trees we will have a list for each tree containing every row used to generate that tree. So we have 10 lists of rows used.

Then we use this list to figure out for each row in the original dataset which trees it was not used in. For instance if row 0 is used in every even tree we would store the values [1, 3, 5, 7, 9] to signify these are the trees we need to use to predict its class. Then we take a prediction from each of these trees, store it, then take the most frequent prediction and store it as the predicted class for row 0.

We then take all of these predictions from every row in the original dataset that had at least 1 tree that it was not used in. And use these predictions to generate a confusion matrix.

In [123]:
def outOfBag(dataset, nTrees, nFeatures=0):
    #notIn is a list containing the examples not used in each of our trees so we dont need to rerun the not in sample
    notIn = []
    #sampleNotInList is a list that tracks every row from the original dataset that wasn't used in at least 1 tree
    sampleNotInList = []
    #Class results stores what class is predicted by all the trees the example isnt used in
    classResults = []
    
    rf = RandomForest(dataset, nTrees, nFeatures)
    
    #We generated the random forest with the full dataset, then for each sample used generate a not in list
    for sample in rf.samples:
        notIn.append(examples_not_in_sample(dataset.examples, sample))
    
    #For every row in the original dataset
    for i in range (dataset.N):
        #We will be predicting a class with trees it wasn't used in
        classes = []
        #For each tree we check if the row is used in that tree, then if it wasnt used in that tree, predict the class for that row
        for j in range (nTrees):
            if i in notIn[j].index:
                classes.append(rf.classifiers[j].predict(dataset.examples.iloc[i]))
        #If we have predictions because it wasn't used in at least 1 tree
        if classes:
            #Find the most often predicted class, append it to results, append the row to the notInList item
            classes = st.mode(classes).mode[0]
            classResults.append(classes)
            sampleNotInList.append(dataset.examples.iloc[i])
    
    #Using the list of rows that are not in at least 1 tree generate a dataframe, and then a dataset
    notInDF = pd.DataFrame(sampleNotInList)
    notInDS = my.DataSet(notInDF, y=True)
    
    #Generate a confusion matrix based on all of our predictions and how accurate they were
    cm = my.confusion_matrix(notInDS.target, np.array(classResults))
    accuracy = np.trace(cm) / np.sum(cm)
    
    print (cm)
    print('Out of bag accuracy with ' + str(nTrees) + ' trees: ', accuracy)

In [124]:
outOfBag(ds, 10)
outOfBag(ds, 15)
outOfBag(ds, 20)

[[370  11]
 [ 35 343]]
Out of bag accuracy with 10 trees:  0.9393939393939394
[[378   6]
 [ 23 361]]
Out of bag accuracy with 15 trees:  0.9622395833333334
[[379   5]
 [ 33 351]]
Out of bag accuracy with 20 trees:  0.9505208333333334
